### ISSUE TITLE
Bagaimana cara run program ini? 

### ISSUE THREAD

**Issue by fajarwahyu99** [riochr17/Sentence-Similarity-ID#1]
Bagaimana cara run program ini?? 
Metode apa yang digunakan?

**Comment by riochr17** [comment]
![ss](https://image.ibb.co/jNOJWd/Screen_Shot_2018_06_30_at_18_33_27.png)

ini contoh mulai clone sampai running

**Comment by riochr17** [comment]
silahkan diikuti dahulu instruksi di readme, jika ada kendala bisa ditanyakan lagi
metode yang digunakan tertulis jelas di readme.
